name: flutter_list_anime
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.6
  flutter:
    sdk: flutter
  http: ^0.13.6
  connectivity_plus: ^5.0.2
  intl: ^0.18.1
  font_awesome_flutter: ^10.7.0
  readmore: ^2.2.0
  youtube_player_flutter: ^9.0.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.15.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/profilePicture.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/profilePicture.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/profilePicture.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/profilePicture.png'
